export const commentdummy = [
  {
    BenutzerName: "محمد امیر",
    BenutzerId: "123456",
    ProduktId: "12313",
    KommentarBody: "این یک متن تست می باشد ",
    createDate: "12/5/1",
    KommentarThema: "این خوب بود",
    Stark: [],
    schwache: ["ضعف", "ضعف", "ضعف", "ضعف"],
  },
  {
    BenutzerName: "محمد امیر",
    BenutzerId: "123456",
    ProduktId: "12313",
    KommentarBody: "این یک متن تست می باشد ",
    createDate: "12/5/1",
    KommentarThema: "این خوب بود",
    Stark: ["قوی", "قوی", "قوی", "قوی"],
    schwache: ["ضعف", , "ضعف", "ضعف"],
  },
  {
    BenutzerName: "محمد امیر",
    BenutzerId: "123456",
    ProduktId: "12313",
    KommentarBody: "این یک متن تست می باشد ",
    createDate: "12/5/1",
    KommentarThema: "این خوب بود",
    Stark: ["قوی", "قوی", "قوی", "قوی"],
    schwache: ["ضعف", "ضعف", "ضعف", "ضعف"],
  },
  {
    BenutzerName: "محمد امیر",
    BenutzerId: "123456",
    ProduktId: "12313",
    KommentarBody: "این یک متن تست می باشد ",
    createDate: "12/5/1",
    KommentarThema: "این خوب بود",
    Stark: ["قوی", "قوی", "قوی", "قوی"],
    schwache: ["ضعف", "ضعف", "ضعف", "ضعف"],
  },
];
