export const BlogDataDummy = [
  {
    id: "1",
    title: "چیدمان مبلمان منزل",
    datetime: "اردیبهشت اول",
    link: "#",
    author: "David",
    image: "blog1.jpg",
  },
  {
    id: "2",
    title: "چیدمان مبلمان منزل",
    datetime: "اردیبهشت اول",
    link: "#",
    author: "David",
    image: "blog2.jpg",
  },
  {
    id: "3",
    title: "چیدمان مبلمان منزل",
    datetime: "اردیبهشت اول",
    link: "#",
    author: "David",
    image: "blog3.jpg",
  },
  {
    id: "4",
    title: "چیدمان مبلمان منزل",
    datetime: "اردیبهشت اول",
    link: "#",
    author: "David",
    image: "blog4.jpg",
  },
  {
    id: "5",
    title: "چیدمان مبلمان منزل",
    datetime: "اردیبهشت اول",
    link: "#",
    author: "David",
    image: "blog1.jpg",
  },
  {
    id: "6",
    title: "This  is Test",
    datetime: "3.5.2022",
    link: "#",
    author: "David",
    image: "blog2.jpg",
  },
];