export const ProductsDummy = [
  {
    Id: "",
    Pname: "مبل مخملی قرمز",
    Price: "10000",
    Discount: "50%",
    imgone: "p1a.png",
    imgtwo: "p1b.png",
  },
  {
    Id: "",
    Pname: "صندلی راحتی لوکس سفید",
    Price: "10000",
    Discount: "50%",
    imgone: "p2a.png",
    imgtwo: "p2b.png",
  },
  {
    Id: "",
    Pname: "صندلی راحتی استیل طلایی",
    Price: "10000",
    Discount: "50%",
    imgone: "p3a.png",
    imgtwo: "p3b.png",
  },
  {
    Id: "",
    Pname: "سالن لوکس تجاری",
    Price: "10000",
    Discount: "50%",
    imgone: "p4a.png",
    imgtwo: "p4b.png",
  },
  {
    Id: "",
    Pname: "مبل لوکس شرکتی",
    Price: "10000",
    Discount: "50%",
    imgone: "p5a.png",
    imgtwo: "p5b.png",
  },
  {
    Id: "",
    Pname: "مبل مخملی قرمز",
    Price: "10000",
    Discount: "50%",
    imgone: "p1a.png",
    imgtwo: "p1b.png",
  },
  {
    Id: "",
    Pname: "صندلی راحتی لوکس سفید",
    Price: "10000",
    Discount: "50%",
    imgone: "p2a.png",
    imgtwo: "p2b.png",
  },
  {
    Id: "",
    Pname: "صندلی راحتی استیل طلایی",
    Price: "10000",
    Discount: "50%",
    imgone: "p3a.png",
    imgtwo: "p3b.png",
  },
  {
    Id: "",
    Pname: "سالن لوکس تجاری",
    Price: "10000",
    Discount: "50%",
    imgone: "p4a.png",
    imgtwo: "p4b.png",
  },
  {
    Id: "",
    Pname: "مبل لوکس شرکتی",
    Price: "10000",
    Discount: "50%",
    imgone: "p5a.png",
    imgtwo: "p5b.png",
  },
];
export const ProductsDummyTwo = [
  {
    Id: "",
    Pname: "مبل مخملی قرمز",
    Price: "50000",
    Discount: "50%",
    imgone: "p1a.png",
    imgtwo: "p1b.png",
  },
  {
    Id: "",
    Pname: "صندلی راحتی لوکس سفید",
    Price: "10000",
    Discount: "50%",
    imgone: "p2a.png",
    imgtwo: "p2b.png",
  },
  {
    Id: "",
    Pname: "صندلی راحتی استیل طلایی",
    Price: "10000",
    Discount: "50%",
    imgone: "p3a.png",
    imgtwo: "p3b.png",
  },
  {
    Id: "",
    Pname: "سالن لوکس تجاری",
    Price: "10000",
    Discount: "50%",
    imgone: "p4a.png",
    imgtwo: "p4b.png",
  },
  {
    Id: "",
    Pname: "مبل لوکس شرکتی",
    Price: "10000",
    Discount: "50%",
    imgone: "p5a.png",
    imgtwo: "p5b.png",
  },
  {
    Id: "",
    Pname: "مبل مخملی قرمز",
    Price: "10000",
    Discount: "50%",
    imgone: "p1a.png",
    imgtwo: "p1b.png",
  },
  {
    Id: "",
    Pname: "صندلی راحتی لوکس سفید",
    Price: "10000",
    Discount: "50%",
    imgone: "p2a.png",
    imgtwo: "p2b.png",
  },
  {
    Id: "",
    Pname: "صندلی راحتی استیل طلایی",
    Price: "10000",
    Discount: "50%",
    imgone: "p3a.png",
    imgtwo: "p3b.png",
  },
  {
    Id: "",
    Pname: "سالن لوکس تجاری",
    Price: "10000",
    Discount: "50%",
    imgone: "p4a.png",
    imgtwo: "p4b.png",
  },
  {
    Id: "",
    Pname: "مبل لوکس شرکتی",
    Price: "10000",
    Discount: "50%",
    imgone: "p5a.png",
    imgtwo: "p5b.png",
  },
];
